version: '3.1'

services:

  php-fpm:
    build: docker
    container_name: 'php'
    environment:
      - LOGS_PATH=/logs
      - DATABASE_URL=mysql://root:@mysql:3306/symfony_logs_viewer?serverVersion=8.0
    volumes:
      - ./:/app
      - ./tmp/logs:/logs
    working_dir: /app

  nginx:
    image: nginx
    container_name: 'nginx'
    working_dir: /app
    ports:
      - 8088:80
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  mysql:
    image: mysql:8
    ports:
      - 3307:3306
    container_name: 'mysql'
    working_dir: /app
    restart: always
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_TEST_DATABASE=${DB_TEST_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - SERVICE_TAGS=dev
      - SERVICE_NAME=mysql
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
